export const TOKEN =
  "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5dXVzaGFkb2xvcmVzQGdtYWlsLmNvbSIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTcyNDg1ODU4NywiZXhwIjoxNzI0OTQ0OTg3fQ.sdWjP33T2MIol2zfFg_LN5InollObgkFXo_Ol0th79M";
